### ISSUE TITLE
🐛 [BUG] - 401 報表無法generate

### ISSUE THREAD

**Issue by TinyMurky** [CAFECA-IO/iSunFA#2327]
### Searched for similar issues

- [ ] YES, I have searched for similar issues.

### Time of occurrence

2024/9/9

### Device

None

### OS

Linux

### Reproduction URL

https://isunfa.com/users/reports/financials/view/10000003?report_type=report-401

### Reproduction steps

```markdown
1. 按下generate 401, report 沒有東西
```

### Current Result

```markdown
1. 按下generate 401, report 沒有東西
```

### Screenshots

![image](https://github.com/user-attachments/assets/596ff418-d58d-45f6-8d93-1ceb3eb8d37b)
![image](https://github.com/user-attachments/assets/a6e6c723-6d2d-4fbd-9615-ee42a141edc0)

### Expected Result

```markdown
1. 希望可以正常generate
```

**Comment by TinyMurky** [comment]
發現原因其實是因為company沒有kyc不能用401 generate, 但是使用者還是按的到
目前先請前端把沒有kyc的ㄍcompany阻斷401功能
後端邏輯是正確的
```bash
 ▲ Next.js 14.2.6
  - Local:        http://localhost:3000

 ✓ Starting...
 ✓ Ready in 906ms
[10:37:08.209] ERROR (24625): Forbidden
    userId: -1
    errorType: "generateReport"
    errorMessage: "haha"
    err: {
      "type": "Error",
      "message": "Forbidden",
      "stack":
          Error: Forbidden
              at A.generate401Report (/home/tinymurky/my_code/專案/ISun/iSunFA/.next/server/pages/api/v1/company/[companyId]/report.js:9:29672)
              at async A.generateReport (/home/tinymurky/my_code/專案/ISun/iSunFA/.next/server/pages/api/v1/company/[companyId]/report.js:9:31613)
              at async M (/home/tinymurky/my_code/專案/ISun/iSunFA/.next/server/pages/api/v1/company/[companyId]/report.js:9:35213)
              at async x (/home/tinymurky/my_code/專案/ISun/iSunFA/.next/server/pages/api/v1/company/[companyId]/report.js:9:35486)
              at async B (/home/tinymurky/my_code/專案/ISun/iSunFA/.next/server/pages/api/v1/company/[companyId]/report.js:9:36458)
              at async V (/home/tinymurky/my_code/專案/ISun/iSunFA/.next/server/pages/api/v1/company/[companyId]/report.js:9:36690)
              at async K (/home/tinymurky/my_code/專案/ISun/iSunFA/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:16853)
              at async U.render (/home/tinymurky/my_code/專案/ISun/iSunFA/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:17492)
              at async NextNodeServer.runApi (/home/tinymurky/my_code/專案/ISun/iSunFA/node_modules/next/dist/server/next-server.js:600:9)
              at async NextNodeServer.handleCatchallRenderRequest (/home/tinymurky/my_code/專案/ISun/iSunFA/node_modules/next/dist/server/next-server.js:269:37)
    }
```
